### ISSUE TITLE
Current build (23/04/2017) breaks scss code.

### ISSUE THREAD

**Issue by LucaCappelletti94** [akalongman/sublimetext-codeformatter#300]
The current build breaks scss code by adding spaces after &:nth-child, but not in case of filter such as &:hover or &:before. Also, it does not format properly curly brackets, with an error di one or more spaces.
What information would you require? (Sublime text 3, build 3126, macOs)

As it should be:
```scss
div{
  &: nth-child(odd) {
    background-color: red;
  }
}
```
As it becomes:
```scss
div{
  &:  nth-child(odd) {
    background-color: red;
  }
}
```
