### ISSUE TITLE
[SCSS-JS]New line with children rules

### ISSUE THREAD

**Issue by notrealdev** [akalongman/sublimetext-codeformatter#380]
Hi everyone, i have some question
I have block sass, js code, how to reformater from
```scss
.footer-widget {
	float: left;
	width: 100%;
	padding: 55px 0 70px 0;
	.widget {
		float: left;
	}
}
```

to ( need new line with each children rules )
```scss
.footer-widget {
	float: left;
	width: 100%;
	padding: 55px 0 70px 0;

	.widget {
		float: left;
	}
}
```

from
```js
var red = false;
if ( !red ) {
...
}
```

to ( need space after ! and variable )
```js
var red = false;
if ( ! red ) {
...
}
```
